<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ac0285a73f02',
		'title' => 'Events - Custom Fields',
		'fields' => array(
			array(
				'key' => 'field_5ac02876a724e',
				'label' => 'Start Date',
				'name' => 'e_start_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'Y-m-d',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5ac028bfa724f',
				'label' => 'End Date',
				'name' => 'e_end_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'Y-m-d',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5ac02aa3a619f',
				'label' => 'Link',
				'name' => 'e_link',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_5ac02b47a61a0',
				'label' => 'Start Time',
				'name' => 'e_start_time',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g:i a',
			),
			array(
				'key' => 'field_5ae37a0556153',
				'label' => 'End Time',
				'name' => 'e_end_time',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'g:i a',
				'return_format' => 'g:i a',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'events',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5accff678c474',
		'title' => 'Flexible Template - Custom Fields',
		'fields' => array(
			array(
				'key' => 'field_5accff85b14b3',
				'label' => 'Main Flexible Content',
				'name' => 'main_flexible_content',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5accff8c784c2' => array(
						'key' => '5accff8c784c2',
						'name' => 'two_columns',
						'label' => 'Two Columns',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5acd0021b14b5',
								'label' => 'Layout Style',
								'name' => 'layout_style',
								'type' => 'radio',
								'instructions' => 'Select the content layout style',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'basic' => 'Basic',
									'intro' => 'Intro',
									'sidebar' => 'Section with Sidebar',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Basic',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5acd0075b14b6',
								'label' => 'Left Column',
								'name' => 'left_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5acd00b2b14b7',
										'label' => 'Left Media Type',
										'name' => 'left_media_type',
										'type' => 'radio',
										'instructions' => 'Select left media type',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5acd0f347b3f5',
										'label' => 'Left Text',
										'name' => 'left_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd00b2b14b7',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5acd0f507b3f6',
										'label' => 'Left Image',
										'name' => 'left_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd00b2b14b7',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5acd0f697b3f7',
										'label' => 'Left Gallery',
										'name' => 'left_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd00b2b14b7',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5acd0f807b3f8',
										'label' => 'Left Video',
										'name' => 'left_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd00b2b14b7',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
							array(
								'key' => 'field_5acd010e6e629',
								'label' => 'Right Column',
								'name' => 'right_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5acd0fc274fcc',
										'label' => 'Right Media Type',
										'name' => 'right_media_type',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5acd0fe574fcd',
										'label' => 'Right Text',
										'name' => 'right_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd0fc274fcc',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5acd0ff674fce',
										'label' => 'Right Image',
										'name' => 'right_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd0fc274fcc',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5acd100f74fcf',
										'label' => 'Right Gallery',
										'name' => 'right_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd0fc274fcc',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5acd104374fd0',
										'label' => 'Right Video',
										'name' => 'right_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5acd0fc274fcc',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b04a95dfc580' => array(
						'key' => '5b04a95dfc580',
						'name' => 'two_columns_label',
						'label' => 'Two Columns with Label',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b04b948e862b',
								'label' => 'Layout Style',
								'name' => 'layout_style',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'white' => 'White',
									'gray' => 'Gray',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5b04a999fc58e',
								'label' => 'Label',
								'name' => 'label_two_columns',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b04a95dfc582',
								'label' => 'Left Column',
								'name' => 'left_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b04a95dfc583',
										'label' => 'Left Media Type',
										'name' => 'left_media_type',
										'type' => 'radio',
										'instructions' => 'Select left media type',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5b04a95dfc584',
										'label' => 'Left Text',
										'name' => 'left_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc583',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b04a95dfc585',
										'label' => 'Left Image',
										'name' => 'left_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc583',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04a95dfc586',
										'label' => 'Left Gallery',
										'name' => 'left_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc583',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04a95dfc587',
										'label' => 'Left Video',
										'name' => 'left_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc583',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
							array(
								'key' => 'field_5b04a95dfc588',
								'label' => 'Right Column',
								'name' => 'right_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b04a95dfc589',
										'label' => 'Right Media Type',
										'name' => 'right_media_type',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5b04a95dfc58a',
										'label' => 'Right Text',
										'name' => 'right_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc589',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b04a95dfc58b',
										'label' => 'Right Image',
										'name' => 'right_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc589',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04a95dfc58c',
										'label' => 'Right Gallery',
										'name' => 'right_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc589',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04a95dfc58d',
										'label' => 'Right Video',
										'name' => 'right_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04a95dfc589',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b04b12117f4f' => array(
						'key' => '5b04b12117f4f',
						'name' => 'three_columns',
						'label' => 'Three Column',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b04b5b0d674f',
								'label' => 'Layout Style',
								'name' => 'layout_style',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'white' => 'White',
									'gray' => 'Gray',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5b04b12117f51',
								'label' => 'Left Column',
								'name' => 'left_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b04b12117f52',
										'label' => 'Left Media Type',
										'name' => 'left_media_type',
										'type' => 'radio',
										'instructions' => 'Select left media type',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5b04b12117f53',
										'label' => 'Left Text',
										'name' => 'left_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f52',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b04b12117f54',
										'label' => 'Left Image',
										'name' => 'left_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f52',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b12117f55',
										'label' => 'Left Gallery',
										'name' => 'left_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f52',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b12117f56',
										'label' => 'Left Video',
										'name' => 'left_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f52',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
							array(
								'key' => 'field_5b04b14517f5d',
								'label' => 'Center Column',
								'name' => 'center_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b04b14517f5e',
										'label' => 'Center Media Type',
										'name' => 'center_media_type',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'vertical',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5b04b14517f5f',
										'label' => 'Center Text',
										'name' => 'center_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b14517f5e',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b04b14517f60',
										'label' => 'Center Image',
										'name' => 'center_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b14517f5e',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b14517f61',
										'label' => 'Center Gallery',
										'name' => 'center_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b14517f5e',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b14517f62',
										'label' => 'Center Video',
										'name' => 'center_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b14517f5e',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
							array(
								'key' => 'field_5b04b12117f57',
								'label' => 'Right Column',
								'name' => 'right_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b04b12117f58',
										'label' => 'Right Media Type',
										'name' => 'right_media_type',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Text' => 'Text',
											'Image' => 'Image',
											'Gallery' => 'Gallery',
											'Video' => 'Video',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => '',
										'return_format' => '',
									),
									array(
										'key' => 'field_5b04b12117f59',
										'label' => 'Right Text',
										'name' => 'right_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f58',
													'operator' => '==',
													'value' => 'Text',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5b04b12117f5a',
										'label' => 'Right Image',
										'name' => 'right_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f58',
													'operator' => '==',
													'value' => 'Image',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => '',
										'preview_size' => 'thumbnail',
										'library' => '',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b12117f5b',
										'label' => 'Right Gallery',
										'name' => 'right_gallery',
										'type' => 'gallery',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f58',
													'operator' => '==',
													'value' => 'Gallery',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'insert' => 'append',
										'library' => '',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5b04b12117f5c',
										'label' => 'Right Video',
										'name' => 'right_video',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b04b12117f58',
													'operator' => '==',
													'value' => 'Video',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'5acd016c4c48f' => array(
						'key' => '5acd016c4c48f',
						'name' => 'call_to_action_block',
						'label' => 'Call to Action Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5acd108a62b93',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5acd10a862b94',
								'label' => 'Button 1',
								'name' => 'button_1',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
							array(
								'key' => 'field_5acd10c162b95',
								'label' => 'Button 2',
								'name' => 'button_2',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
							array(
								'key' => 'field_5acd10d962b96',
								'label' => 'Background Color',
								'name' => 'background_color',
								'type' => 'button_group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'none' => 'None',
									'gold' => 'Gold',
									'red' => 'Red',
									'dark_blue' => 'Dark Blue',
								),
								'allow_null' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5acd111662b97' => array(
						'key' => '5acd111662b97',
						'name' => 'headline',
						'label' => 'Headline',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5acd113462b98',
								'label' => 'Headline Text',
								'name' => 'headline_text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5acd117b62b9a',
								'label' => 'Layout Style',
								'name' => 'layout_style',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'primary' => 'Primary',
									'secondary_white' => 'Secondary White',
									'secondary_gray' => 'Secondary Gray',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5acd124b73ced' => array(
						'key' => '5acd124b73ced',
						'name' => 'related_content_layout',
						'label' => 'Related Content ',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5acd126673cee',
								'label' => 'Related Historic Sites',
								'name' => 'related_historic_sites',
								'type' => 'taxonomy',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'taxonomy' => 'historic_sites',
								'field_type' => 'checkbox',
								'allow_null' => 0,
								'add_term' => 1,
								'save_terms' => 0,
								'load_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array(
								'key' => 'field_5ace61fdb8f48',
								'label' => 'Related Work',
								'name' => 'related_work',
								'type' => 'taxonomy',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'taxonomy' => 'our_work',
								'field_type' => 'checkbox',
								'allow_null' => 0,
								'add_term' => 1,
								'save_terms' => 0,
								'load_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'5acd1379a034c' => array(
						'key' => '5acd1379a034c',
						'name' => 'images',
						'label' => 'Image(s)',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ae0dcaf031db',
								'label' => 'Container Images',
								'name' => 'container_images',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 1,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5ae0dd09031dc',
										'label' => '',
										'name' => 'content_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'uploadedTo',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'custom-page-templates/flexible-template.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ab98646b0ba0',
		'title' => 'Historic Site - Main Section',
		'fields' => array(
			array(
				'key' => 'field_5aba8a4b6707c',
				'label' => 'Main Section',
				'name' => 'hs_main_section',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ab986569d106',
						'label' => 'Banner Image',
						'name' => 'hs_banner_image',
						'type' => 'image',
						'instructions' => 'Add the image of this historic site',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'banner_size',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ab98877c1a2d',
						'label' => 'Title',
						'name' => 'hs_title',
						'type' => 'text',
						'instructions' => 'Enter Historic Site Title',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5aeb3b3062abd',
						'label' => 'Main Content',
						'name' => 'main_content',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5ab9b5f6fc461',
								'label' => 'Site Text',
								'name' => 'hs_site_text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aeb3c59055b2',
								'label' => 'Right Column',
								'name' => 'right_column',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_5ab989081fa66',
										'label' => 'Address',
										'name' => 'hs_address',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
									array(
										'key' => 'field_5ab988a039f0c',
										'label' => 'Hours',
										'name' => 'hs_hours',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
					),
					array(
						'key' => 'field_5ab9b59b1a706',
						'label' => 'Main Gallery',
						'name' => 'hs_main_gallery',
						'type' => 'gallery',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'min' => '',
						'max' => '',
						'insert' => 'append',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5aeb363ab12c8',
						'label' => 'Caption Gallery',
						'name' => 'hs_caption_gallery',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5aeb37edce0af',
				'label' => 'Plan Your Visit',
				'name' => 'hs_plan_your_visit',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5ab9b66415220',
						'label' => 'Visit Text',
						'name' => 'hs_visit_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5aeb392ff94ab',
						'label' => 'Right Column',
						'name' => 'right_column',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5ab9b627815e3',
								'label' => 'Visit Map',
								'name' => 'hs_visit_map',
								'type' => 'google_map',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'center_lat' => '',
								'center_lng' => '',
								'zoom' => '',
								'height' => 300,
							),
							array(
								'key' => 'field_5aeb3946f94ac',
								'label' => 'Hours & Directions',
								'name' => 'hs_visit_hours_directions',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5aecc030fbbfa',
				'label' => 'HighLight Information',
				'name' => 'hs_highlight_information',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5aecc051fbbfb',
						'label' => 'Image',
						'name' => 'hs_highlight_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'uploadedTo',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5aecc0a2fbbfc',
						'label' => 'Right Column',
						'name' => 'hs_highlight_right_column',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aecc0c3fbbfd',
								'label' => 'Title',
								'name' => 'hs_highlight_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aecc0d4fbbfe',
								'label' => 'Content',
								'name' => 'hs_highlight_content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aecc0fafbbff',
								'label' => 'Button',
								'name' => 'hs_highlight_button',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5ab9b722dae67',
				'label' => 'Admission Information',
				'name' => 'hs_admission_info',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeb6c768a92e',
						'label' => 'Intro Text',
						'name' => 'hs_admission_intro_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5aeb6cc48a92f',
						'label' => 'Admission Content',
						'name' => 'hs_admission_content',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5aeb6e5031ae3',
								'label' => 'Left Content',
								'name' => 'hr_admission_left_content',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_5aeb6d468a931',
										'label' => 'Pricing Table',
										'name' => 'hs_admission_pricing_table',
										'type' => 'table',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'use_header' => 2,
									),
									array(
										'key' => 'field_5aeb6d068a930',
										'label' => 'Pricing Text',
										'name' => 'hs_admission_pricing_text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
							array(
								'key' => 'field_5aeb6dba8a932',
								'label' => 'Contact Text',
								'name' => 'hs_admission_contact_text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5aeb73ac42857',
				'label' => 'Donate Information',
				'name' => 'hs_donate_info',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeb742d42858',
						'label' => 'Images',
						'name' => 'hs_donate_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'banner_size',
						'library' => 'uploadedTo',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ab9b76b9c004',
						'label' => 'Donate Button Link',
						'name' => 'hs_donate_button_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
					),
				),
			),
			array(
				'key' => 'field_5aeb7e349d297',
				'label' => 'Tours & Site Rental',
				'name' => 'hs_tours_and_site_rental',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_5ab9b9cad2d09',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
			array(
				'key' => 'field_5aeb7ae0b39ce',
				'label' => 'Key Visitor Info',
				'name' => 'hs_key_visitor_info',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeb7b5eb39cf',
						'label' => 'Location & Arrival',
						'name' => 'hs_key_visitor_info_location_and_arrival',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5aeb7b7ab39d0',
						'label' => 'Rules & Regulations',
						'name' => 'hs_key_visitor_info_rules_and_regulations',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'custom-page-templates/historic-site.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ab9b9cad2d09',
		'title' => 'Historic Site - Tours & Site Rental',
		'fields' => array(
			array(
				'key' => 'field_5aeb783770ee6',
				'label' => 'Tours & Site Rental',
				'name' => 'h2_tours_site_rental_info',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeb785870ee7',
						'label' => 'Intro Text',
						'name' => 'hs_tour_site_renta_intro_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5aeb799c7709a',
						'label' => 'Tour Content',
						'name' => 'hs_tour_content',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5aeb788c70ee8',
								'label' => 'Content Left',
								'name' => 'content_left',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_5aeb78e970ee9',
										'label' => 'Site Rental & Special Events',
										'name' => 'hs_tour_site_rental_special_events',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
									array(
										'key' => 'field_5aeb792a70eea',
										'label' => 'Group Tour Bookings',
										'name' => 'hs_tour_group_tour_bookings',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
									array(
										'key' => 'field_5aeb808184bcf',
										'label' => 'Table Prices',
										'name' => 'hr_tour_table_prices',
										'type' => 'table',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'use_header' => 2,
									),
								),
							),
							array(
								'key' => 'field_5aeb79dc7709c',
								'label' => 'Contact',
								'name' => 'hr_tour_contact',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'custom-page-templates/historic-site.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5aedd821c2e18',
		'title' => 'Homepage - Custom Fields',
		'fields' => array(
			array(
				'key' => 'field_5aedd96858776',
				'label' => 'Intro Banner',
				'name' => 'hp_intro_banner',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeddabb5877a',
						'label' => 'Background Image',
						'name' => 'hp_intro_bg_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'Home Banner',
						'library' => 'uploadedTo',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5aeddc835877b',
						'label' => 'Center Column',
						'name' => 'hp_intro_center_column',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aeddcea5877c',
								'label' => 'Heading',
								'name' => 'hp_intro_heading',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aeddcf85877d',
								'label' => 'Subheading',
								'name' => 'hp_intro_subheading',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aeddd065877e',
								'label' => 'Button',
								'name' => 'hp_intro_button',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5aedde5ffc684',
				'label' => 'Our Work',
				'name' => 'hp_our_work',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5aedde8dfc685',
						'label' => 'Focus 1',
						'name' => 'hp_work_focus_1',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aeddf94fc688',
								'label' => 'Icon',
								'name' => 'hp_work_focus_1_icon',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5aeddf13fc686',
								'label' => 'Title',
								'name' => 'hp_work_focus_1_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aeddf6afc687',
								'label' => 'Description',
								'name' => 'hp_work_focus_1_description',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aede01cfc689',
								'label' => 'Link',
								'name' => 'hp_work_focus_1_link',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
					array(
						'key' => 'field_5aede051fc68a',
						'label' => 'Focus 2',
						'name' => 'hp_work_focus_2',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aede11bfc68d',
								'label' => 'Icon',
								'name' => 'hp_work_focus_2_icon',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'uploadedTo',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5aede0f0fc68b',
								'label' => 'Title',
								'name' => 'hp_work_focus_2_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aede10bfc68c',
								'label' => 'Description',
								'name' => 'hp_work_focus_2_description',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aede190fc68e',
								'label' => 'Link',
								'name' => 'hp_work_focus_2_link',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
					array(
						'key' => 'field_5aede1a1fc68f',
						'label' => 'Focus 3',
						'name' => 'hp_work_focus_3',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aede1dffc692',
								'label' => 'Icon',
								'name' => 'hp_work_focus_3_icon',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'uploadedTo',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5aede1bafc690',
								'label' => 'Title',
								'name' => 'hp_work_focus_3_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aede1d5fc691',
								'label' => 'Description',
								'name' => 'hp_work_focus_3_description',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aede204fc693',
								'label' => 'Link',
								'name' => 'hp_work_focus_3_link',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5aede392bea0a',
				'label' => 'Intro Banner Temporarily',
				'name' => 'hp_intro_banner_temporarily',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5aede3f285fd0',
						'label' => 'Enable',
						'name' => 'hp_intro_temp_enable',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5aede43385fd1',
						'label' => 'Content',
						'name' => 'hp_intro_temp_content',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5aede3f285fd0',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5aede943eb517',
								'label' => 'Featured Image',
								'name' => 'hp_intro_temp_featured_content_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5aede9fbeb518',
								'label' => 'Heading',
								'name' => 'hp_intro_temp_featured_content_heading',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5aedea26eb519',
								'label' => 'Description',
								'name' => 'hp_intro_temp_featured_content_description',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'visual',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5aedea46eb51a',
								'label' => 'Button',
								'name' => 'hp_intro_temp_featured_content_button',
								'type' => 'link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5aedeb1903992',
				'label' => 'Gallery',
				'name' => 'hp_gallery',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aeded859ea9f',
						'label' => '',
						'name' => 'hp_images_container',
						'type' => 'gallery',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'min' => 3,
						'max' => 7,
						'insert' => 'append',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array(
				'key' => 'field_5aeded5d9ea9e',
				'label' => 'Historic Sites Navigator',
				'name' => 'hp_historic_sites_navigator',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aedee33b2852',
						'label' => 'Intro Text',
						'name' => 'hp_historic_nav_intro_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5aedef1c78478',
				'label' => 'Call to Donate',
				'name' => 'hp_call_to_donate',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aedef4678479',
						'label' => 'Text',
						'name' => 'hp_call_to_donate_text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5aedef7c7847a',
						'label' => 'Button',
						'name' => 'hp_call_to_donate_button',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
			array(
				'key' => 'field_5aedf01041d60',
				'label' => 'Featured Post',
				'name' => 'hp_featured_blog',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5aedf04541d61',
						'label' => 'Post',
						'name' => 'hp_featured_blog_post',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'post',
						),
						'taxonomy' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'custom-page-templates/homepage-site.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5af5b0a5508fa',
		'title' => 'Options Theme',
		'fields' => array(
			array(
				'key' => 'field_5af5af2aa4ed1',
				'label' => 'Footer Info',
				'name' => 'opt_footer',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5af5af4fa4ed2',
						'label' => 'Address',
						'name' => 'opt_footer_address',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5af9fa4ed3',
						'label' => 'Phone number',
						'name' => 'opt_footer_phone',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5aff13d85c',
						'label' => 'Fax number',
						'name' => 'opt_footer_fax',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5b01e3d85d',
						'label' => 'Email',
						'name' => 'opt_footer_email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '34',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_5af5b159151a2',
				'label' => 'Subscribe',
				'name' => 'opt_subscribe',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5af5b162151a3',
						'label' => 'Subscribe link',
						'name' => 'opt_subscribe_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5b317151a4',
						'label' => 'Subscribe html/javascript code snippet',
						'name' => 'opt_subscribe_snippet',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_5af5b3a16709f',
				'label' => 'Social Links',
				'name' => 'opt_social',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5af5b3cf670a0',
						'label' => 'Facebook',
						'name' => 'opt_social_facebook',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5b402670a1',
						'label' => 'Twitter',
						'name' => 'opt_social_twitter',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5b42e670a2',
						'label' => 'Instagram',
						'name' => 'opt_social_instagram',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5af5b49e670a3',
						'label' => 'YouTube',
						'name' => 'opt_social_youtube',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;
?>
