<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ac0285a73f02',
	'title' => 'Events - Custom Fields',
	'fields' => array(
		array(
			'key' => 'field_5ac02876a724e',
			'label' => 'Start Date',
			'name' => 'e_start_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5ac028bfa724f',
			'label' => 'End Date',
			'name' => 'e_end_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5ac02aa3a619f',
			'label' => 'Link',
			'name' => 'e_link',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5ac02b47a61a0',
			'label' => 'Time',
			'name' => 'e_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5accff678c474',
	'title' => 'Flexible Template - Custom Fields',
	'fields' => array(
		array(
			'key' => 'field_5accff85b14b3',
			'label' => 'Main Flexible Content',
			'name' => 'main_flexible_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5accff8c784c2' => array(
					'key' => '5accff8c784c2',
					'name' => 'two_columns',
					'label' => 'Two Columns',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5acd0021b14b5',
							'label' => 'Layout Style',
							'name' => 'layout_style',
							'type' => 'radio',
							'instructions' => 'Select the content layout style',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Basic' => 'Basic',
								'Intro' => 'Intro',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'Basic',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5acd0075b14b6',
							'label' => 'Left Column',
							'name' => 'left_column',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5acd00b2b14b7',
									'label' => 'Left Media Type',
									'name' => 'left_media_type',
									'type' => 'radio',
									'instructions' => 'Select left media type',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Text' => 'Text',
										'Image' => 'Image',
										'Gallery' => 'Gallery',
										'Video' => 'Video',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5acd0f347b3f5',
									'label' => 'Left Text',
									'name' => 'left_text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd00b2b14b7',
												'operator' => '==',
												'value' => 'Text',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_5acd0f507b3f6',
									'label' => 'Left Image',
									'name' => 'left_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd00b2b14b7',
												'operator' => '==',
												'value' => 'Image',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5acd0f697b3f7',
									'label' => 'Left Gallery',
									'name' => 'left_gallery',
									'type' => 'gallery',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd00b2b14b7',
												'operator' => '==',
												'value' => 'Gallery',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'min' => '',
									'max' => '',
									'insert' => 'append',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5acd0f807b3f8',
									'label' => 'Left Video',
									'name' => 'left_video',
									'type' => 'oembed',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd00b2b14b7',
												'operator' => '==',
												'value' => 'Video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'width' => '',
									'height' => '',
								),
							),
						),
						array(
							'key' => 'field_5acd010e6e629',
							'label' => 'Right Column',
							'name' => 'right_column',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5acd0fc274fcc',
									'label' => 'Right Media Type',
									'name' => 'right_media_type',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Text' => 'Text',
										'Image' => 'Image',
										'Gallery' => 'Gallery',
										'Video' => 'Video',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5acd0fe574fcd',
									'label' => 'Right Text',
									'name' => 'right_text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd0fc274fcc',
												'operator' => '==',
												'value' => 'Text',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_5acd0ff674fce',
									'label' => 'Right Image',
									'name' => 'right_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd0fc274fcc',
												'operator' => '==',
												'value' => 'Image',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5acd100f74fcf',
									'label' => 'Right Gallery',
									'name' => 'right_gallery',
									'type' => 'gallery',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd0fc274fcc',
												'operator' => '==',
												'value' => 'Gallery',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'min' => '',
									'max' => '',
									'insert' => 'append',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5acd104374fd0',
									'label' => 'Right Video',
									'name' => 'right_video',
									'type' => 'oembed',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5acd0fc274fcc',
												'operator' => '==',
												'value' => 'Video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'width' => '',
									'height' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'5acd016c4c48f' => array(
					'key' => '5acd016c4c48f',
					'name' => 'call_to_action_block',
					'label' => 'Call to Action Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5acd108a62b93',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5acd10a862b94',
							'label' => 'Button 1',
							'name' => 'button_1',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5acd10c162b95',
							'label' => 'Button 2',
							'name' => 'button_2',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5acd10d962b96',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'none' => 'none',
								'gold' => 'gold',
								'light blue' => 'light blue',
								'dark blue' => 'dark blue',
							),
							'allow_null' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5acd111662b97' => array(
					'key' => '5acd111662b97',
					'name' => 'headline',
					'label' => 'Headline',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5acd113462b98',
							'label' => 'Headline Text',
							'name' => 'headline_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5acd114362b99',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'none' => 'none',
								'gold' => 'gold',
								'light blue' => 'light blue',
								'dark blue' => 'dark blue',
								'light gray' => 'light gray',
							),
							'allow_null' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5acd117b62b9a',
							'label' => 'Layout Style',
							'name' => 'layout_style',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Primary' => 'Primary',
								'Secondary' => 'Secondary',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5acd124b73ced' => array(
					'key' => '5acd124b73ced',
					'name' => 'related_content_layout',
					'label' => 'Related Content ',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5acd126673cee',
							'label' => 'Related Content',
							'name' => 'related_content',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'historic_sites',
							'field_type' => 'checkbox',
							'allow_null' => 0,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5acd1379a034c' => array(
					'key' => '5acd1379a034c',
					'name' => 'images',
					'label' => 'Image(s)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5acd138ba034d',
							'label' => 'Image Count',
							'name' => 'image_count',
							'type' => 'select',
							'instructions' => 'Select how many images you want to display in this block',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1',
								2 => '2',
								3 => '3',
							),
							'default_value' => array(
								0 => 1,
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5acd13b8a034e',
							'label' => 'Image 1',
							'name' => 'image_1',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '1',
									),
								),
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '2',
									),
								),
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5acd13d7a034f',
							'label' => 'Image 2',
							'name' => 'image_2',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '2',
									),
								),
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5acd141aa0354',
							'label' => 'Image 3',
							'name' => 'image_3',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5acd138ba034d',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'custom-page-templates/flexible-template.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ab98646b0ba0',
	'title' => 'Historic Site - Main Section',
	'fields' => array(
		array(
			'key' => 'field_5aba8a4b6707c',
			'label' => 'Main Section',
			'name' => 'hs_main_section',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ab986569d106',
					'label' => 'Banner Image',
					'name' => 'hs_banner_image',
					'type' => 'image',
					'instructions' => 'Add the image of this historic site',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5ab9b59b1a706',
					'label' => 'Main Gallery',
					'name' => 'hs_main_gallery',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => '',
					'insert' => 'append',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5ab98877c1a2d',
					'label' => 'Title',
					'name' => 'hs_title',
					'type' => 'text',
					'instructions' => 'Enter Historic Site Title',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5ab988a039f0c',
					'label' => 'Year of Origination',
					'name' => 'hs_year_of_origination',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5ab989081fa66',
					'label' => 'Address',
					'name' => 'hs_address',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5ab9b5f6fc461',
					'label' => 'Site Text',
					'name' => 'hs_site_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5ab9b627815e3',
					'label' => 'Visit Map',
					'name' => 'hs_visit_map',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => '',
				),
				array(
					'key' => 'field_5ab9b66415220',
					'label' => 'Visit Text',
					'name' => 'hs_visit_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5ab9b68ab3791',
			'label' => 'Contact Information',
			'name' => 'hs_contact_info',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9b6b85acc2',
			'label' => 'Hours Information',
			'name' => 'hs_hours_info',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9b722dae67',
			'label' => 'Admission Information',
			'name' => 'hs_admission_info',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9b75be343d',
			'label' => 'Additional Information',
			'name' => 'hs_additional_info',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9b76b9c004',
			'label' => 'Donate Button Link',
			'name' => 'hs_donate_button_link',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5ab9b7bd0c02b',
			'label' => 'Upcoming Events',
			'name' => 'hs_upcoming_events',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5ab9b84a3f294',
			'label' => 'Related Stories',
			'name' => 'hs_related_stories',
			'type' => 'wysiwyg',
			'instructions' => 'List of related blog posts in the category matching this historic site. Will include:
Post Title
Link to event posting',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'custom-page-templates/historic-site.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ab9b9cad2d09',
	'title' => 'Historic Site - Tours & Site Rental',
	'fields' => array(
		array(
			'key' => 'field_5ab9ba4cc7c05',
			'label' => 'Invitation to Rent',
			'name' => 'hs_invitation_to_rent',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9ba8a172dc',
			'label' => 'List of Rental or Special Events',
			'name' => 'hs_list_of_rental_or_special_events',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5ab9baf9e32b6',
			'label' => 'Group Tour Booking Text',
			'name' => 'hs_group_tour_booking_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ab9bb21ee57f',
			'label' => 'Group Tour Booking Rates',
			'name' => 'hs_group_tour_booking_rates',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'custom-page-templates/historic-site.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>
